YOLO_BOX_CAT_IDX = 0
YOLO_BOX_XCENTER_IDX = 1
YOLO_BOX_YCENTER_IDX = 2
YOLO_BOX_WIDTH_IDX = 3
YOLO_BOX_HEIGHT_IDX = 4

YOLO_PT_CAT_IDX = 0
YOLO_PT_X_IDX = 1
YOLO_PT_Y_IDX = 2

COCO_BOX_XMIN_IDX = 0
COCO_BOX_YMIN_IDX = 1
COCO_BOX_WIDTH_IDX = 2
COCO_BOX_HEIGHT_IDX = 3

INPUT_FORMAT_Y_IDX = 0
INPUT_FORMAT_X_IDX = 1

PATCH_XSTART_IDX = 0
PATCH_YSTART_IDX = 1

MAX_OVERHANG_BXS = 0.85
PT_VIS_CIRCLE_RADIUS = 2